package io.github.pocketflow.nodes;

import io.github.pocketflow.Node;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Mirrors {@code CombineTutorial} from nodes.py. */
public class CombineTutorial extends Node {

    private static final class Prep {
        String outputPath;
        String indexContent;
        List<Map<String, String>> chapterFiles;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Object prep(Map<String, Object> shared) {
        String projectName = (String) shared.get("project_name");
        String outputBaseDir = (String) shared.getOrDefault("output_dir", "output");
        String outputPath = Path.of(outputBaseDir, projectName).toString();
        String repoUrl = (String) shared.getOrDefault("repo_url", "");

        Models.Relationships relationships = (Models.Relationships) shared.get("relationships");
        List<Integer> chapterOrder = (List<Integer>) shared.get("chapter_order");
        List<Models.Abstraction> abstractions = (List<Models.Abstraction>) shared.get("abstractions");
        List<Object> chaptersContent = (List<Object>) shared.get("chapters");

        // --- Mermaid diagram ---
        List<String> mermaidLines = new ArrayList<>();
        mermaidLines.add("flowchart TD");
        for (int i = 0; i < abstractions.size(); i++) {
            String nodeId = "A" + i;
            String sanitized = abstractions.get(i).name.replace("\"", "");
            mermaidLines.add("    " + nodeId + "[\"" + sanitized + "\"]");
        }
        for (Models.Relationship rel : relationships.details) {
            String fromId = "A" + rel.from;
            String toId = "A" + rel.to;
            String edgeLabel = rel.label.replace("\"", "").replace("\n", " ");
            if (edgeLabel.length() > 30) {
                edgeLabel = edgeLabel.substring(0, 27) + "...";
            }
            mermaidLines.add("    " + fromId + " -- \"" + edgeLabel + "\" --> " + toId);
        }
        String mermaidDiagram = String.join("\n", mermaidLines);

        // --- index.md ---
        StringBuilder index = new StringBuilder("# Tutorial: ").append(projectName).append("\n\n");
        index.append(relationships.summary).append("\n\n");
        index.append("**Source Repository:** [").append(repoUrl).append("](").append(repoUrl).append(")\n\n");
        index.append("```mermaid\n").append(mermaidDiagram).append("\n```\n\n");
        index.append("## Chapters\n\n");

        List<Map<String, String>> chapterFiles = new ArrayList<>();
        for (int i = 0; i < chapterOrder.size(); i++) {
            int abstractionIndex = chapterOrder.get(i);
            if (abstractionIndex >= 0 && abstractionIndex < abstractions.size() && i < chaptersContent.size()) {
                String abstractionName = abstractions.get(abstractionIndex).name;
                String safeName = sanitize(abstractionName);
                String filename = String.format("%02d_%s.md", i + 1, safeName);
                index.append(i + 1).append(". [").append(abstractionName).append("](").append(filename).append(")\n");

                String content = (String) chaptersContent.get(i);
                if (!content.endsWith("\n\n")) {
                    content += "\n\n";
                }
                content += "---\n\nGenerated by [AI Codebase Knowledge Builder](https://github.com/The-Pocket/Tutorial-Codebase-Knowledge)";
                Map<String, String> cf = new LinkedHashMap<>();
                cf.put("filename", filename);
                cf.put("content", content);
                chapterFiles.add(cf);
            } else {
                System.out.println("Warning: Mismatch between chapter order, abstractions, or content at index "
                        + i + " (abstraction index " + abstractionIndex + "). Skipping.");
            }
        }
        index.append("\n\n---\n\nGenerated by [AI Codebase Knowledge Builder](https://github.com/The-Pocket/Tutorial-Codebase-Knowledge)");

        Prep prep = new Prep();
        prep.outputPath = outputPath;
        prep.indexContent = index.toString();
        prep.chapterFiles = chapterFiles;
        return prep;
    }

    @Override
    public Object exec(Object prepResult) {
        Prep p = (Prep) prepResult;
        System.out.println("Combining tutorial into directory: " + p.outputPath);
        try {
            Files.createDirectories(Path.of(p.outputPath));
            Path indexFile = Path.of(p.outputPath, "index.md");
            Files.writeString(indexFile, p.indexContent);
            System.out.println("  - Wrote " + indexFile);

            for (Map<String, String> cf : p.chapterFiles) {
                Path chapterFile = Path.of(p.outputPath, cf.get("filename"));
                Files.writeString(chapterFile, cf.get("content"));
                System.out.println("  - Wrote " + chapterFile);
            }
        } catch (IOException e) {
            throw new RuntimeException("Failed to write tutorial files: " + e.getMessage(), e);
        }
        return p.outputPath;
    }

    @Override
    public void post(Map<String, Object> shared, Object prepResult, Object execResult) {
        shared.put("final_output_dir", execResult);
        System.out.println("\nTutorial generation complete! Files are in: " + execResult);
    }

    private static String sanitize(String name) {
        StringBuilder sb = new StringBuilder();
        for (char c : name.toCharArray()) {
            sb.append(Character.isLetterOrDigit(c) ? c : '_');
        }
        return sb.toString().toLowerCase();
    }
}
